### ISSUE TITLE
Error while writing fibonacci.png

### ISSUE THREAD

**Issue by Iftakharpy** [Bishalsarang/Recursion-Tree-Visualizer#2] opened 2020-07-28 19:24 UTC
@Bishalsarang  installed the script with pip. Then copied the fibonacci code and saved in a name.py file tried to run but it failed to make png file and gif file but it created a folder "frames" and "fibonacci.gif" file. Would you please help me fix the  issue?

# Code:
```python
# Author: Bishal Sarang

# Import Visualiser class from module visualiser
from visualiser.visualiser import Visualiser as vs

# Add decorator
# Decorator accepts optional arguments: ignore_args , show_argument_name, show_return_value and node_properties_kwargs
@vs(node_properties_kwargs={"shape":"record", "color":"#f57542", "style":"filled", "fillcolor":"grey"})
def fib(n):
    if n <= 1:
        return n
    return fib(n=n - 1) + fib(n=n - 2)


def main():
    # Call function
    print(fib(n=6))
    # Save recursion tree to a file
    vs.make_animation("fibonacci.gif", delay=2)


if __name__ == "__main__":
    main()
```

# Output:
```python
8
Starting to make animation
Writing fibonacci.png failed
Writing frames....
Error writing frames
Writing gif...
Error saving gif.
```

# Folder Structrue:
![issue](https://user-images.githubusercontent.com/37600593/88712749-0af08800-d13c-11ea-9182-6591e73d0232.PNG)

-

**Comment by Bishalsarang** [comment] 2020-07-28 20:12
Did you correctly install graphviz binary and added to the PATH?

**Comment by Bishalsarang** [comment] 2020-07-28 20:23
@Iftakharpy Iftakharpy 
Try running the following code in your terminal.
`dot -V`

You should expect output something like this:
`dot - graphviz version 2.38.0 (20140413.2041)`
![image](https://user-images.githubusercontent.com/11006583/88717315-1776df80-d140-11ea-98ae-dd868f71c877.png)

If you get sth like:
```
'dot' is not recognized as an internal or external command,
operable program or batch file.
```
Try installing graphviz binary and don't forget to add it to the System PATH as mentioned in the instructions
If the problem still exists feel free to reach out.

**Comment by Iftakharpy** [comment] 2020-07-28 23:31
My bad I forgot to install Graphviz but now I installed Graphviz and added it to Path. But now another error occured.
![Capture](https://user-images.githubusercontent.com/37600593/88739571-ab56a480-d15c-11ea-9635-e484cc69c792.PNG)

**Comment by Bishalsarang** [comment] 2020-07-29 04:13
Have you installed all the requirements from requirements.txt?

**Comment by Bishalsarang** [comment] 2020-07-29 04:13
It seems like it's still working on my end.

**Comment by Bishalsarang** [comment] 2020-07-29 04:20
Try installing the requirements using 
`pip install -r requirements.txt`

If you haven't already.

Confirm the packages inside requirements.txt are installed correctly by running

`pip freeze `

If the issue still gets unresolved we can try running from the source itself without installing from the pip.  Feel free to ping back

**Comment by Iftakharpy** [comment] 2020-07-29 13:20
## Yeah I had installed the requirements but to make sure there is not issue with the versions of the requirements I reinstalled the required packages with the versions specified in requirements.txt but still I got the same error as previous comment.

## I also tried cloning this repository and running
>python setup.py install
## Then I tried running code from the first comment and changed the import statement to "from visualiser import Visualiser as vs" from "\Recursion-Tree-Visualizer\build\lib\visualiser" directory.
## Then I tried to run the same code from "\Recursion-Tree-Visualizer\visualiser>" directory. But no luck same error as #issuecomment-665346310 
# looking forward to hearing from you

**Comment by Bishalsarang** [comment] 2020-07-29 14:56
Luckily, I was able to reproduce the error by following steps:

- Uninstalled previously installed Graphviz 

- Removed the Graphviz bin from  the PATH

- Created a new environment using virtualenv and pip installed recursion-visualiser

Then to simulate the error, I downloaded the graphviz binary version(win 64) you are using from [here](
https://www2.graphviz.org/Packages/stable/windows/10/cmake/Release/x64/)
![image](https://user-images.githubusercontent.com/11006583/88814599-08447000-d1da-11ea-907b-7d6f80689928.png)

I think the issue is with the Graphviz version. To resolve the error I again uninstalled the Graphviz binary and removed from PATH.
Then I downloaded the win32 zip from [here](https://www2.graphviz.org/Packages/stable/windows/10/msbuild/Release/Win32/)

![image](https://user-images.githubusercontent.com/11006583/88815720-5dcd4c80-d1db-11ea-9bec-2b644f8561b2.png)

I hope this fixed the error.

If the issue is solved using the above method, please close the issue, otherwise, feel free to post the error message so we can resolve the issue.

**Comment by Iftakharpy** [comment] 2020-07-29 20:56
# Thank you, man, this worked.
This is a great project. I run this with merge sort. This worked but made a gif put all the recursive calls side by side.
![fibonacci](https://user-images.githubusercontent.com/37600593/88852258-d6e69700-d20f-11ea-97a5-7fdd9832cae3.gif)
# It would be great if this would show them like your demo Fibonacci gif
I am a beginner so I don't know how can I modify the script. If I could I would modify the script and contribute to it. I hope you will make this work. But I totally understand if you don't.

**Comment by Bishalsarang** [comment] 2020-07-30 16:26
Can you send me the particular implementation that produced the above result?
I currently don't have any plans on updating the package.
 Maybe I can come back and look in the future if I plan on upgrading with major improvements.

Good luck on your recursion journey 👍. Hope it helps

**Comment by Iftakharpy** [comment] 2020-07-30 19:55
# Code is provided below.
```python
# Author: Bishal Sarang

# Import Visualiser class from module visualiser
from visualiser.visualiser import Visualiser as vs



#O(n+m)
def alternative_merge(array1,array2): #this function is easier to read
    merged_array=[]

    array1_index = 0
    array2_index = 0
    while array1_index<len(array1) and array2_index<len(array2):
        if array1[array1_index]<array2[array2_index]:
            merged_array.append(array1[array1_index])
            array1_index+=1
        else:
            merged_array.append(array2[array2_index])
            array2_index+=1

    #if we dodn't added numbers from one of the lists then add them to the merged list now
    while array1_index<len(array1):
        merged_array.append(array1[array1_index])
        array1_index+=1
    while array2_index<len(array2):
        merged_array.append(array2[array2_index])
        array2_index+=1

    #return the merged array
    return merged_array



#time complexity is O(nlog(n)) because we are recursively calling the merge_sort function n times
#where time complexity of the left_slice or right_slice is O(log(n))
#O(nlog(n)) - time
#space complexity is n because we are splitting the list in n smaller arrays
#O(n) - space
@vs(node_properties_kwargs={"shape":"record", "color":"#f57542", "style":"filled", "fillcolor":"grey"})
def merge_sort(array):
    if len(array)<=1:
        return array

    mid_index = len(array)//2
    left_slice = merge_sort(array[:mid_index]) #O(log(n))
    right_slice = merge_sort(array[mid_index:]) #O(log(n))
    return alternative_merge(left_slice,right_slice) #O(n+m)


def main():
    # Call function
    print(merge_sort([5,0,1,9]))
    # Save recursion tree to a file
    vs.make_animation("merge_sort.gif", delay=1.3)


if __name__ == "__main__":
    main()
```

**Comment by Bishalsarang** [comment] 2020-11-09 04:08
![merge_sort](https://user-images.githubusercontent.com/11006583/98499284-3160ac00-2271-11eb-8f15-6ef09debb9fd.gif)
![merge_sort](https://user-images.githubusercontent.com/11006583/98499289-345b9c80-2271-11eb-862f-eadf2ca158e2.png)

@Iftakharpy Are these the expected result you wanted for above code.
I think I can make it work. Please confirm if this is the expected result

**Closed** 2020-11-10 02:28 UTC
Labels: question
